---
# tasks file for install terraform on Windows system

- name: Windows | Find all versions of Terraform
  win_uri:
    url: https://releases.hashicorp.com/terraform/index.json
    return_content: yes
  register: terraform_index

- name: Windows | Finds the latest Terraform version when latest var is define
  set_fact:
    terraform_version: "{{ (terraform_index.content | from_json).versions | reject('search','-') | list | sort_versions | last }}"
  when: terraform_version == 'latest'

# This task avoids downloading Terraform every time
- name: Windows | Check if terraform is present on Windows with the right version
  win_shell: terraform --version
  register: terraform_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Windows | Download Terraform
  win_get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_windows_amd64.zip
    dest: C:\tmp\terraform_{{ terraform_version }}_windows_amd64.zip
  when:
    - terraform_version not in terraform_installed_version.stdout

- name: Windows | Create Terraform folder
  win_file:
    path: "{{ terraform_path }}"
    state: directory

- name: Windows | Install Terraform
  win_unzip:
    src: C:\tmp\terraform_{{ terraform_version }}_windows_amd64.zip
    dest: "{{ terraform_path }}"
    creates: "{{ terraform_path }}terraform.exe"
  when:
    - terraform_version not in terraform_installed_version.stdout

- name: Windows | Add Terraform to PATH
  win_path:
    elements: "{{ terraform_path }}"
