---
- name: Verify
  hosts: all
  tasks:
  - name: Solaris | Terraform should be functionnal
    command: terraform --version
    ignore_errors: yes
    register: terraform_result

  - name: Solaris | Verify commands outputs
    assert:
      that:
        - terraform_result.rc == 0
      success_msg: "All tests passed"
